exp_10:
  batch_size: '128'
  buffer_size: 1e8
  first_hidden_size: 1024
  gamma: 0.9
  gradient_steps: '100'
  learning_rate: 3e-4
  learning_starts: '10000'
  num: 10
  second_hidden_size: 1024
  seed: 10
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.2'
  train_freq: 10
exp_12:
  batch_size: '256'
  buffer_size: 1e7
  first_hidden_size: 512
  gamma: 0.95
  gradient_steps: '1'
  learning_rate: 3e-4
  learning_starts: '10000'
  num: 12
  second_hidden_size: 64
  seed: 10
  target_entropy: -200.0
  target_update_interval: '10'
  tau: '0.05'
  train_freq: 10
exp_13:
  batch_size: '256'
  buffer_size: 1e8
  first_hidden_size: 128
  gamma: 0.9
  gradient_steps: '100'
  learning_rate: 3e-4
  learning_starts: '100000'
  num: 13
  second_hidden_size: 128
  seed: 10
  target_entropy: -20.0
  target_update_interval: '1'
  tau: 0.05
  train_freq: 1
exp_15:
  batch_size: '128'
  buffer_size: 1e7
  first_hidden_size: 1024
  gamma: '0.9'
  gradient_steps: '1'
  learning_rate: 3e-5
  learning_starts: '10000'
  num: 15
  second_hidden_size: 512
  seed: 10
  target_entropy: -2.0
  target_update_interval: '10'
  tau: 0.1
  train_freq: 100
exp_16:
  batch_size: 256
  buffer_size: 1e7
  first_hidden_size: 512
  gamma: '0.95'
  gradient_steps: '10'
  learning_rate: 3e-3
  learning_starts: '10000'
  num: 16
  second_hidden_size: 256
  seed: 10
  target_entropy: -20.0
  target_update_interval: '5'
  tau: '0.2'
  train_freq: 10000
exp_17:
  batch_size: '256'
  buffer_size: 1e8
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 3e-3
  learning_starts: '10000'
  num: 17
  second_hidden_size: 256
  seed: 10
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  train_freq: 10
exp_18:
  batch_size: '512'
  buffer_size: 1e7
  first_hidden_size: 64
  gamma: '0.99'
  gradient_steps: '1'
  learning_rate: 3e-5
  learning_starts: '1000'
  num: 18
  second_hidden_size: 512
  seed: 10
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.05'
  train_freq: 1
exp_19:
  batch_size: '128'
  buffer_size: 1e6
  first_hidden_size: 512
  gamma: '0.9'
  gradient_steps: '1'
  learning_rate: 3e-3
  learning_starts: '10000'
  num: 19
  second_hidden_size: 128
  seed: 10
  target_entropy: -2000.0
  target_update_interval: '10'
  tau: '0.05'
  train_freq: 1000
exp_2:
  batch_size: '128'
  buffer_size: 1e8
  first_hidden_size: 512
  gamma: '0.9'
  gradient_steps: '10'
  learning_rate: 3e-5
  learning_starts: '1000'
  num: 2
  second_hidden_size: 1024
  seed: 10
  target_entropy: -20.0
  target_update_interval: '10'
  tau: '0.1'
  train_freq: 100
exp_21:
  batch_size: '512'
  buffer_size: 1e7
  first_hidden_size: 128
  gamma: '0.95'
  gradient_steps: '100'
  learning_rate: 3e-5
  learning_starts: '1000'
  num: 21
  second_hidden_size: 64
  seed: 10
  target_entropy: -2000.0
  target_update_interval: '5'
  tau: '0.1'
  train_freq: 10000
exp_22:
  batch_size: '256'
  buffer_size: 1e6
  first_hidden_size: 128
  gamma: '0.99'
  gradient_steps: '10'
  learning_rate: 3e-4
  learning_starts: '10000'
  num: 22
  second_hidden_size: 1024
  seed: 10
  target_entropy: -0.2
  target_update_interval: '5'
  tau: '0.2'
  train_freq: 100
exp_24:
  batch_size: 128
  buffer_size: 1e7
  first_hidden_size: 256
  gamma: '0.95'
  gradient_steps: '1'
  learning_rate: 3e-4
  learning_starts: '100000'
  num: 24
  second_hidden_size: 64
  seed: 10
  target_entropy: -0.2
  target_update_interval: '10'
  tau: '0.1'
  train_freq: 100
exp_26:
  batch_size: '128'
  buffer_size: 1000000
  first_hidden_size: 256
  gamma: '0.99'
  gradient_steps: 100
  learning_rate: 3e-3
  learning_starts: '1000'
  num: 26
  second_hidden_size: 1024
  seed: 10
  target_entropy: -2.0
  target_update_interval: '10'
  tau: '0.2'
  train_freq: 10000
exp_29:
  batch_size: '256'
  buffer_size: 10000000
  first_hidden_size: 1024
  gamma: '0.99'
  gradient_steps: '100'
  learning_rate: 3e-4
  learning_starts: '100000'
  num: 29
  second_hidden_size: 512
  seed: 10
  target_entropy: -2000.0
  target_update_interval: 5
  tau: 0.05
  train_freq: 100
exp_3:
  batch_size: '512'
  buffer_size: 1e7
  first_hidden_size: 64
  gamma: '0.9'
  gradient_steps: '10'
  learning_rate: 3e-4
  learning_starts: '10000'
  num: 3
  second_hidden_size: 256
  seed: 10
  target_entropy: -2000.0
  target_update_interval: '1'
  tau: '0.2'
  train_freq: 1
exp_30:
  batch_size: '512'
  buffer_size: 100000000
  first_hidden_size: 64
  gamma: 0.99
  gradient_steps: 10
  learning_rate: 0.0003
  learning_starts: '1000'
  num: 30
  second_hidden_size: 128
  seed: 10
  target_entropy: -0.2
  target_update_interval: 5
  tau: 0.1
  train_freq: 10
exp_31:
  batch_size: '128'
  buffer_size: 1e6
  first_hidden_size: 256
  gamma: 0.95
  gradient_steps: 10
  learning_rate: 3e-3
  learning_starts: '1000'
  num: 31
  second_hidden_size: 256
  seed: 10
  target_entropy: -20.0
  target_update_interval: '5'
  tau: '0.2'
  train_freq: 1
exp_32:
  batch_size: '256'
  buffer_size: 1e8
  first_hidden_size: 512
  gamma: '0.95'
  gradient_steps: '100'
  learning_rate: 0.0003
  learning_starts: '1000'
  num: 32
  second_hidden_size: 512
  seed: 10
  target_entropy: -2.0
  target_update_interval: 10
  tau: 0.2
  train_freq: 10000
exp_33:
  batch_size: '128'
  buffer_size: 1e8
  first_hidden_size: 512
  gamma: 0.95
  gradient_steps: 10
  learning_rate: 3e-5
  learning_starts: '100000'
  num: 33
  second_hidden_size: 256
  seed: 10
  target_entropy: -0.2
  target_update_interval: '1'
  tau: 0.1
  train_freq: 1000
exp_34:
  batch_size: '512'
  buffer_size: 100000000
  first_hidden_size: 64
  gamma: 0.9
  gradient_steps: 1
  learning_rate: 3e-3
  learning_starts: '100000'
  num: 34
  second_hidden_size: 1024
  seed: 10
  target_entropy: -20.0
  target_update_interval: 1
  tau: 0.05
  train_freq: 1000
exp_35:
  batch_size: 128
  buffer_size: 1000000
  first_hidden_size: 64
  gamma: 0.99
  gradient_steps: '1'
  learning_rate: 0.0003
  learning_starts: '100000'
  num: 35
  second_hidden_size: 1024
  seed: 10
  target_entropy: -200.0
  target_update_interval: 10
  tau: 0.2
  train_freq: 100
exp_36:
  batch_size: 512
  buffer_size: 10000000
  first_hidden_size: 1024
  gamma: 0.9
  gradient_steps: '10'
  learning_rate: 0.003
  learning_starts: 100000
  num: 36
  second_hidden_size: 1024
  seed: 10
  target_entropy: -20.0
  target_update_interval: '10'
  tau: '0.05'
  train_freq: 1
exp_37:
  batch_size: 512
  buffer_size: 1000000
  first_hidden_size: 512
  gamma: '0.9'
  gradient_steps: 1
  learning_rate: 3.0e-05
  learning_starts: 10000
  num: 37
  second_hidden_size: 64
  seed: 10
  target_entropy: -0.2
  target_update_interval: 1
  tau: 0.1
  train_freq: 1
exp_38:
  batch_size: 128
  buffer_size: 1000000
  first_hidden_size: 512
  gamma: '0.99'
  gradient_steps: 1
  learning_rate: 3.0e-05
  learning_starts: 100000
  num: 38
  second_hidden_size: 128
  seed: 10
  target_entropy: -200.0
  target_update_interval: 10
  tau: 0.2
  train_freq: 10000
exp_39:
  batch_size: 128
  buffer_size: 10000000
  first_hidden_size: 128
  gamma: '0.9'
  gradient_steps: 100
  learning_rate: 3.0e-05
  learning_starts: 1000
  num: 39
  second_hidden_size: 512
  seed: 10
  target_entropy: -2000.0
  target_update_interval: 1
  tau: 0.1
  train_freq: 10
exp_4:
  batch_size: '512'
  buffer_size: 1e8
  first_hidden_size: 1024
  gamma: '0.99'
  gradient_steps: '100'
  learning_rate: 3e-3
  learning_starts: '1000'
  num: 4
  second_hidden_size: 256
  seed: 10
  target_entropy: -0.2
  target_update_interval: '10'
  tau: '0.05'
  train_freq: 100
exp_40:
  batch_size: 256
  buffer_size: 10000000
  first_hidden_size: 1024
  gamma: '0.95'
  gradient_steps: 100
  learning_rate: 3.0e-05
  learning_starts: 1000
  num: 40
  second_hidden_size: 64
  seed: 10
  target_entropy: -2.0
  target_update_interval: 5
  tau: 0.1
  train_freq: 1000
exp_5:
  batch_size: '512'
  buffer_size: 1e7
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '10'
  learning_rate: 3e-3
  learning_starts: '100000'
  num: 5
  second_hidden_size: 512
  seed: 10
  target_entropy: -2000.0
  target_update_interval: '5'
  tau: '0.05'
  train_freq: 10000
exp_6:
  batch_size: '256'
  buffer_size: 1e6
  first_hidden_size: 1024
  gamma: '0.99'
  gradient_steps: '100'
  learning_rate: 3e-4
  learning_starts: '1000'
  num: 6
  second_hidden_size: 128
  seed: 10
  target_entropy: -0.2
  target_update_interval: '5'
  tau: '0.1'
  train_freq: 1000
exp_7:
  batch_size: '128'
  buffer_size: 1e6
  first_hidden_size: 128
  gamma: '0.95'
  gradient_steps: '1'
  learning_rate: 3e-3
  learning_starts: '100000'
  num: 7
  second_hidden_size: 512
  seed: 10
  target_entropy: -20.0
  target_update_interval: '5'
  tau: '0.2'
  train_freq: 1000
exp_8:
  batch_size: '256'
  buffer_size: 1e6
  first_hidden_size: 64
  gamma: '0.99'
  gradient_steps: '10'
  learning_rate: 3e-5
  learning_starts: '100000'
  num: 8
  second_hidden_size: 128
  seed: 10
  target_entropy: -2.0
  target_update_interval: '5'
  tau: '0.2'
  train_freq: 10
