exp_2:
  batch_size: 128
  buffer_size: 100000000.0
  first_hidden_size: 512
  gamma: 0.9
  gradient_steps: 10
  learning_rate: 3.0e-05
  learning_starts: 1000
  num: 2
  second_hidden_size: 1024
  seed: 10
  target_entropy: -20.0
  target_update_interval: 10
  tau: 0.1
  train_freq: 100
exp_3:
  batch_size: 512
  buffer_size: 10000000.0
  first_hidden_size: 64
  gamma: 0.9
  gradient_steps: 10
  learning_rate: 0.0003
  learning_starts: 10000
  num: 3
  second_hidden_size: 256
  seed: 10
  target_entropy: -2000.0
  target_update_interval: 1
  tau: 0.2
  train_freq: 1
exp_4:
  batch_size: 512
  buffer_size: 100000000.0
  first_hidden_size: 1024
  gamma: 0.99
  gradient_steps: 100
  learning_rate: 0.003
  learning_starts: 1000
  num: 4
  second_hidden_size: 256
  seed: 10
  target_entropy: -0.2
  target_update_interval: 10
  tau: 0.05
  train_freq: 100
exp_5:
  batch_size: 512
  buffer_size: 10000000.0
  first_hidden_size: 256
  gamma: 0.9
  gradient_steps: 10
  learning_rate: 0.003
  learning_starts: 100000
  num: 5
  second_hidden_size: 512
  seed: 10
  target_entropy: -2000.0
  target_update_interval: 5
  tau: 0.05
  train_freq: 10000
exp_6:
  batch_size: 256
  buffer_size: 1000000.0
  first_hidden_size: 1024
  gamma: 0.99
  gradient_steps: 100
  learning_rate: 0.0003
  learning_starts: 1000
  num: 6
  second_hidden_size: 128
  seed: 10
  target_entropy: -0.2
  target_update_interval: 5
  tau: 0.1
  train_freq: 1000
exp_7:
  batch_size: 128
  buffer_size: 1000000.0
  first_hidden_size: 128
  gamma: 0.95
  gradient_steps: 1
  learning_rate: 0.003
  learning_starts: 100000
  num: 7
  second_hidden_size: 512
  seed: 10
  target_entropy: -20.0
  target_update_interval: 5
  tau: 0.2
  train_freq: 1000
