sac_rs_1:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 1
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_19:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 19
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_28:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 28
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_41:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 41
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_59:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 59
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_60:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 60
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_71:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 71
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_72:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 72
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_92:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 92
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_98:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 98
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
