sac_rs_15:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 15
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 1000
  train_freq: 10
sac_rs_3:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 3
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 1000
  train_freq: 10
sac_rs_34:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 34
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 1000
  train_freq: 10
sac_rs_4:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 4
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 1000
  train_freq: 10
sac_rs_50:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 50
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 1000
  train_freq: 10
sac_rs_58:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 58
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 1000
  train_freq: 10
sac_rs_81:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 81
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 1000
  train_freq: 10
sac_rs_82:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 82
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 1000
  train_freq: 10
sac_rs_9:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 9
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 1000
  train_freq: 10
sac_rs_95:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 95
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 1000
  train_freq: 10
