sac_rs_411:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 411
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_437:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 437
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_476:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 476
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_496:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 496
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_597:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 597
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_700:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 700
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_711:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 711
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_733:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 733
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_906:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 906
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
sac_rs_908:
  batch_size: '256'
  buffer_size: 100000000
  first_hidden_size: 256
  gamma: '0.9'
  gradient_steps: '100'
  learning_rate: 0.003
  learning_starts: '10000'
  second_hidden_size: 256
  seed: 908
  target_entropy: -200.0
  target_update_interval: '1'
  tau: '0.1'
  total_timesteps: 100000
  train_freq: 10
